- key: install-cli--test-default
  call: $LEAF_DIGEST

- key: install-cli--test-default--assert
  use: install-cli--test-default
  run: "kubectl version --client | grep 'Client Version: v'"

- key: install-cli--test-specified
  call: $LEAF_DIGEST
  with:
    cli-version: "1.28.7"

- key: install-cli--test-specified--assert
  use: install-cli--test-specified
  run: "kubectl version --client | grep 'Client Version: v1.28.7'"
