- key: docker--login--test
  call: $LEAF_DIGEST
  with:
    username: ${{ vaults.mint_leaves_development.secrets.DOCKER_HUB_USERNAME }}

- key: docker--login--test--assert-with-password-env
  use: docker--login--test
  docker: true
  run: |
    set +e
    cat ~/.docker/config.json | jq -e '.auths | has("https://index.docker.io/v1/")' > /dev/null
    if [ $? -ne 0 ]; then
      >&2 echo "Expected auths for https://index.docker.io/v1/ in ~/.docker/config.json"
      exit 1
    fi
  env:
    DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

- key: docker--login--test--assert-without-password-env--logged-in-before
  use: [docker--login--test, docker--login--test--assert-with-password-env]
  docker: true
  run: |
    set +e
    [ -e ~/.docker/config.json ] || exit 0

    cat ~/.docker/config.json | jq -e '.auths | has("https://index.docker.io/v1/")' > /dev/null
    if [ $? -eq 0 ]; then
      >&2 echo "Expected no auths for https://index.docker.io/v1/ in ~/.docker/config.json"
      exit 1
    fi

- key: docker--login--test--assert-without-password-env--not-logged-in-before
  use: docker--login--test
  docker: true
  run: |
    set +e
    [ -e ~/.docker/config.json ] || exit 0

    cat ~/.docker/config.json | jq -e '.auths | has("https://index.docker.io/v1/")' > /dev/null
    if [ $? -eq 0 ]; then
      >&2 echo "Expected no auths for https://index.docker.io/v1/ in ~/.docker/config.json"
      exit 1
    fi
